apiVersion: v1
kind: Service
metadata:
  name: clinic-api
  namespace: harbor-clinic
spec:
  selector:
    app: clinic-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
